[package]
name = "deck"          # The name of the package
version = "0.1.0"      # The current version of the package
edition = "2021"       # The Rust edition being used

[dependencies]
rand = "0.8.5"         # Dependency on the 'rand' crate for random number generation